make_dataset:
  test_size: 0.1
  random_state: 30

data_preprocessing:
  percentiles:
    - 0.002
    - 0.998

train_model:
  random_forest_regressor:
    n_estimators: 20
    max_depth: 6
    verbose: 2
    n_jobs : -1

  # lightgbm_regressor:
  #   boosting_type: ['gbdt']
  #   num_leaves: [30, 50, 100]
  #   learning_rate: [0.01, 0.1, 0.2]
  #   n_estimators: [100, 200, 500]
  #   max_depth: [-1, 10, 20]
  #   min_data_in_leaf: [20, 50, 100]
  lightgbm_regressor:
    boosting_type: 'gbdt'
    num_leaves: 200
    learning_rate: 0.25
    n_estimators: 1500
    max_depth: 25
    min_data_in_leaf: 100
    n_jobs: -1